name: Readable data changes

on: 
  pull_request:

jobs:
  readable-data-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
            
      - name: Parse asset changes to be more readable
        id: readable-assets
        run: python readableAssets.py
        env:
          REPO: ${{ github.repository }}
          REPO_PATH: ${{ github.workspace }}
          PRNUM: ${{ github.event.number }}
          COMMIT_A: ${{ github.event.pull_request.base.sha }}
          COMMIT_B: ${{ github.event.pull_request.head.sha }}

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ steps.readable-assets.outputs.OUTPUT_MESSAGE }}
